language: python
python:
  - "3.5"
branches:
 only:
 - master
 - devel

install:
 - pip install -e .

script: py.test

after_success:
 - if [[ $TRAVIS_OS_NAME == "linux" ]]; then pip install codecov; codecov; fi
