language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
branches:
 only:
 - master
 - dev

install:
 - pip install -e .

script: py.test

after_success:
 - if [[ $TRAVIS_OS_NAME == "linux" ]]; then pip install codecov; codecov; fi
